version: '3.0'

services:
    loadbalancer:
        image: "aleksas/addresses"
        ports:
            - 80:80
        depends_on:
            - address1
            - address2
            - address3
            - address4
    address1:
        image: "laju2259/addresses:1"
        environment:
            SERVER: 0
        depends_on:
            - company
    address2:
        image: "laju2259/addresses:1"
        environment:
            SERVER: 1
        depends_on:
            - company
    address3:
        image: "laju2259/addresses:1"
        environment:
            SERVER: 2
        depends_on:
            - company
    address4:
        image: "laju2259/addresses:1"
        environment:
            SERVER: 3
        depends_on:
            - company
    company:
        image: "danmerix/company:3"
        ports:
            - 1234:1234